package model

// Model is the record-side contract.
type Model interface {
	Schema() any
}

// FielderSlice is the list-side contract to iterate records without reflection.
type FielderSlice interface {
	Len() int
	At(i int) Model
	Append(m Model)
}

// Decodable represents a type that can be decoded from the wire.
type Decodable interface {
	Decode(data []byte) error
}

// ModelSlice is the list-side mirror of Model: a typed slice of records that can be
// iterated without reflection (FielderSlice) and travel from the wire (Decodable).
//
// It is THE type to name at any boundary that receives a decoded list of records —
// a view reloading its items, a Caller filling a response. Consumers MUST NOT
// declare this intersection locally.
//
// Implementations are generated by ormc — never written by hand.
type ModelSlice interface {
	FielderSlice
	Decodable
}
